version: '3'
services:
  app:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "npm install && npm run web"
    ports:
      - "19006:19006"
      - "8081:8081"